### ISSUE TITLE
Zed fails to start language server "oxc"

### ISSUE THREAD

**Issue by destegabry** [suxiaoshao/zed-oxc#1]
Hi, I just tried the `zed-oxc` extension but it doesn't work on my laptop.

Zed.log contains the following error:

```
2024-09-25T10:00:29.751856+02:00 [ERROR] failed to start language server "oxc": installed package 'oxlint' did not contain expected path '"./node_modules/@oxclint/darwin-arm64/oxc_language_server"'
```

The issue seems to be a wrong binary path reference, the parent folder should be `@oxlint` instead of  `@oxclint`.

This is very strange because the path seems right in the code:
https://github.com/suxiaoshao/zed-oxc/blob/d0d0d0ee5216c442590d12a6e90591b711eb20cb/src/oxc.rs#L12

I see there are no release tags for this extension, is it possible you have to republish it?

**Comment by suxiaoshao** [comment]
I already know what the problem is, and I will fix it in the next couple of days.

**Comment by suxiaoshao** [comment]
The oxc extension of the Zed extensions market has been updated and solved this problem. You can try whether version 0.1.1 has solved this problem.
